nav:
  - Home : 'index.md'
  - Npcs : 'npcs.md'
  - Styles : 'styles.md'

site_name: Skyblock Hud Wiki
site_url: https://skyblockhud-wiki.readthedocs.io/en/latest/
docs_dir: docs

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition


theme:
  name: material
  icon:
    logo: octicons/question-16
  palette:
    scheme: slate
    primary: deep orange
    accent: amber

extra_css:
  - extra.css


site_description: Welcome to the Skyblock Hud wiki!
